services:
  misinfoai_backend:
    image: misinfodetector/backend:latest
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - "misinfoai_backend:/var/lib/backend/"
volumes:
  misinfoai_backend:

